//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LavkaEntities1 : DbContext
    {
        private static LavkaEntities1 _context;

        public LavkaEntities1()
            : base("name=LavkaEntities1")
        {
        }

        public static LavkaEntities1 GetContext()
        {
            if (_context == null)
                _context = new LavkaEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<condition> conditions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<thing> things { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
